name: great_quran
description: Great Quran.

publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  carousel_slider: ^4.0.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  in_app_review: ^2.0.4
  intl: ^0.17.0
  share_plus: ^4.0.3

dev_dependencies:
  change_app_package_name: ^1.0.0
  # flutter_native_splash: ^2.1.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_gravity: center
