name: great_quran
description: Great Quran.

publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:


  ##### ------------------------ UI -------------------------- #####

  loading_indicator: ^3.1.0

  extended_image: ^6.2.1

  shimmer: ^2.0.0

  ##### ------------------------ Data -------------------------- #####

  shared_preferences: ^2.0.15

  ##### ------------------------ State & Bushiness Logic -------------------------- #####

  flutter_riverpod: ^1.0.4

  equatable: ^2.0.3

  json_annotation: ^4.3.0

  event_bus: ^2.0.0

  rxdart: ^0.27.7

  ##### ------------------------ Utilities -------------------------- #####

  overlay_support: ^2.0.1

  audioplayers: ^0.20.1

  carousel_slider: ^4.0.0

  clipboard: ^0.1.3

  share_plus: ^4.0.9

  upgrader: ^4.2.1

  in_app_update: ^3.0.0

  open_store: ^0.2.4

  intl: ^0.17.0

  dio: ^4.0.6

  collection: ^1.16.0

  url_launcher: ^6.0.15


  ##### ------------------------ Flutter Dependencies -------------------------- #####

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  in_app_review: ^2.0.4


dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/fonts/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android_gravity: center
